#!/bin/bash
# =============================================================
# setup-xcode.sh
# Creates the Xcode project scaffolding for DailyBriefSticky
# Run from the repo root: chmod +x setup-xcode.sh && ./setup-xcode.sh
# Requires: Xcode command line tools (xcode-select --install)
# =============================================================

echo "🔨 Setting up DailyBriefSticky Xcode project..."
echo ""
echo "IMPORTANT: Xcode project files (.xcodeproj) must be created through Xcode's UI."
echo "Follow these steps exactly:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1 — Create project in Xcode"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • Open Xcode"
echo "  • File → New → Project"
echo "  • Choose: macOS → App"
echo "  • Product Name: DailyBriefSticky"
echo "  • Bundle Identifier: com.kanjali17.DailyBriefSticky"
echo "  • Interface: SwiftUI"
echo "  • Language: Swift"
echo "  • Storage: SwiftData ✓ (check this box)"
echo "  • Save to: THIS folder (the repo root)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2 — Delete auto-generated files"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Delete from Xcode project navigator (Move to Trash):"
echo "  • ContentView.swift"
echo "  • Item.swift"
echo "  • DailyBriefStickyApp.swift (the auto-generated one)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3 — Add source files from this repo"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  In Xcode: File → Add Files to 'DailyBriefSticky'"
echo "  Select ALL .swift files from DailyBriefSticky/ folder:"
echo ""

find DailyBriefSticky -name "*.swift" | sort | while read f; do
    echo "  ✦ $f"
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4 — Info.plist: add LSUIElement"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • Select DailyBriefSticky target → Info tab"
echo "  • Add key: 'Application is agent (UIElement)' = YES"
echo "  • OR edit Info.plist directly and add:"
echo "    <key>LSUIElement</key>"
echo "    <true/>"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5 — Signing & Capabilities"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • Select your Apple Developer Team"
echo "  • Click '+ Capability' → add 'Outgoing Connections (Client)'"
echo "    (needed for RSS fetch + Anthropic API)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 6 — Build & Run"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⌘R — widget appears top-right, newspaper icon in menu bar"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 7 (Optional) — AI Summaries"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  • Get API key: https://console.anthropic.com"
echo "  • In widget settings: paste key + toggle AI Summaries ON"
echo ""
echo "✅ Setup guide complete!"
